package com.sprk.service.user.enums;

public enum DocumentType {
	DOCUMENT_PROFILE,
	DOCUMENT_IDENTITY_PROOF,
	DOCUMENT_ADDRESS_PROOF,
	DOCUMENT_OFFER_LETTER,
	DOCUMENT_EDUCATION,
	DOCUMENT_EXPERIENCE_LETTER,
	DOCUMENT_SALARY_SLIP
}
